FROM  node:16-alpine

WORKDIR /myapp
RUN apk apk update && apk upgrade && apk update
COPY Server/package.json ./
RUN npm install && npm cache clean --force

COPY  ./Server/src ./src
EXPOSE 3000

CMD [ "node", "src/app.js" ]