---
version: '3.8'
services:
  Nodejs:
    build:
      target: development
    ports:
      - target: 4000
        published: ${DD_PORT:-4000}
        protocol: tcp
        mode: host
    volumes:
      - ./Server/src/:/myapp/src:z
  React:
    build:
      target: development
    volumes:
      - ./Client/src/:/myapp/src:z
      - ./Client/public/:/myapp/public:z
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always
    ports:
      - 8081:80
