FROM  node:16-alpine as base

WORKDIR /myapp
RUN apk apk update && apk upgrade && apk update
COPY Server/package.json ./
RUN npm install && npm cache clean --force

FROM base as production

COPY  ./Server/ .
RUN npm run tsc
EXPOSE 3000

CMD [ "node", "src/app.js" ]

FROM base as development

COPY  ./Server/src ./src
EXPOSE 3000

CMD [ "npm", "run", "dev" ]