---
version: '3.8'
services:
  React:
    build:
      context: ./
      dockerfile: Dockerfile.react
    container_name: react
    image: "react-todo"
    depends_on:
      - Nodejs
    ports:
      - target: 3000
        published: ${DD_PORT:-3000}
        protocol: tcp
        mode: host
  Nodejs:
    build:
      context: ./
      dockerfile: Dockerfile.nodejs
    container_name: nodejs
    image: "nodejs-todo"
    environment:
      DD_DATABASE_URL: ${DD_DATABASE_URL}
    env_file:
      - .env
    links:
      - mysql
  mysql:
    image: mysql:5.7.37@sha256:66d52e6baa8093820c09fec56992a5ee734f17e9fad8ef5ffc31597b231bd048
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWOR: ${MYSQL_ROOT_PASSWOR}
      MYSQL_DATABASE: ${DD_DATABASE_NAME}
      MYSQL_USER: ${DD_DATABASE_USER}
      MYSQL_PASSWORD: ${DD_DATABASE_PASSWORD}
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    volumes:
      - todo_data:/var/lib/mysql
volumes:
  todo_data: {}
