FROM node:14-alpine AS development
ENV NODE_ENV development

WORKDIR /myapp

RUN apk apk update && apk upgrade && apk update

COPY Client/package.json .
RUN yarn install

COPY ./Client/src ./src
COPY ./Client/public ./public

EXPOSE 3000

CMD [ "yarn", "start" ]